[package]
name = "minigit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
clap = { version = "4.5.9", features = ["derive"] }
flate2 = { version = "1.0.30", features = ["zlib"] }
tempfile = "3.10.1"
